
server:
  port: ${PORT:9023}


eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
